<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Jellyfin.Plugin.SSO_Auth</RootNamespace>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Config\configPage.html" />
    <None Remove="Config\config.js" />
    <None Remove="Config\style.css" />
    <None Remove="Config\linking.html" />
    <EmbeddedResource Include="Config\configPage.html" />
    <EmbeddedResource Include="Config\config.js" />
    <EmbeddedResource Include="Config\permissions.js" />
    <EmbeddedResource Include="Config\style.css" />
    <EmbeddedResource Include="Config\linking.html" />
    <EmbeddedResource Include="Config\linking.js" />
    <EmbeddedResource Include="Views\web.js" />
    <EmbeddedResource Include="Views\complete.js" />
    <None Remove="Views\complete.html" />
    <EmbeddedResource Include="Views\complete.html" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Duende.IdentityModel.OidcClient" Version="6.0.1" />
    <PackageReference Include="Microsoft.IdentityModel.JsonWebTokens" Version="8.22.0" />
    <PackageReference Include="ITfoxtec.Identity.Saml2" Version="4.21.0" />
    <PackageReference Include="Jellyfin.Controller" Version="$(JellyfinVersion)" ExcludeAssets="runtime" />
    <PackageReference Include="Jellyfin.Model" Version="$(JellyfinVersion)" ExcludeAssets="runtime" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SerilogAnalyzer" Version="0.15.0" PrivateAssets="All" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.556" PrivateAssets="all" />
    <PackageReference Include="SmartAnalyzers.MultithreadingAnalyzer" Version="1.1.31" PrivateAssets="All" />
  </ItemGroup>

  <PropertyGroup>
    <CodeAnalysisRuleSet>../jellyfin.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SSO-Auth.Tests" />
  </ItemGroup>
</Project>
